#!/bin/bash
# Runs ON THE EC2 HOST. Pulls secrets out of SSM Parameter Store and writes
# /opt/fit/.env for docker compose. Nothing sensitive is ever committed to git
# or baked into an image — the instance role is what grants access.
#
# Usage: ./render-env.sh [aws-region]
set -euo pipefail

REGION="${1:-us-east-1}"
ENV_FILE=/opt/fit/.env

param() {
  aws ssm get-parameter --name "$1" --with-decryption --region "$REGION" \
    --query Parameter.Value --output text 2>/dev/null || echo ""
}

OPENAI_KEY="$(param /fit/openai-api-key)"
GEMINI_KEY="$(param /fit/gemini-api-key)"
ADMIN_EMAIL="$(param /fit/admin-email)"
HOSTNAME_OVERRIDE="$(param /fit/app-hostname)"

# Default hostname: <dashed-public-ip>.sslip.io, which always resolves to this
# box and therefore always passes the Let's Encrypt HTTP challenge.
if [ -z "$HOSTNAME_OVERRIDE" ]; then
  TOKEN=$(curl -sS -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 300")
  PUBLIC_IP=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" \
    http://169.254.169.254/latest/meta-data/public-ipv4)
  APP_HOSTNAME="${PUBLIC_IP//./-}.sslip.io"
else
  APP_HOSTNAME="$HOSTNAME_OVERRIDE"
fi

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by render-env.sh — do not edit by hand, do not commit.
OPENAI_API_KEY=${OPENAI_KEY}
GOOGLE_GEMINI_API_KEY=${GEMINI_KEY}
ADMIN_EMAIL=${ADMIN_EMAIL:-schreyerc@bna-inc.com}
APP_HOSTNAME=${APP_HOSTNAME}
EOF

echo "wrote $ENV_FILE (hostname: $APP_HOSTNAME)"
